# Generated by Django 4.2.7 on 2023-12-11 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bonus_dept_salgrade_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('Country_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Capitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Capital_Name', models.CharField(max_length=100)),
                ('Country_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.countries')),
            ],
        ),
    ]
