# Generated by Django 4.2.7 on 2023-12-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_countries_capitals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.RemoveField(
            model_name='capitals',
            name='Country_Name',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='Deptno',
        ),
        migrations.DeleteModel(
            name='Salgrade',
        ),
        migrations.DeleteModel(
            name='Capitals',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='Dept',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
