# Generated by Django 4.2.7 on 2023-12-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bonus_countries_dept_salgrade_employe_capitals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='MGR',
            new_name='Mgr',
        ),
    ]
