# Generated by Django 4.2.7 on 2023-12-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_employe_comm'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='Email',
            field=models.EmailField(default='India@123gamil.com', max_length=254),
        ),
    ]
